src/ThirdPartyEventEditor/ThirdPartyEventEditor/Controllers/ExportController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Unicode;
using System.Threading.Tasks;
using System.Web.Configuration;
using System.Web.Mvc;
using ThirdPartyEventEditor.Filters;
using ThirdPartyEventEditor.Models;
using ThirdPartyEventEditor.Services;

namespace ThirdPartyEventEditor.Controllers
{
    /// <summary>
    /// Contoller for action, allowing export file.
    /// </summary>
    [Authorize (Roles = "ModeratorExport")]
    [LoggerTimeFilter]
    public class ExportController : Controller
    {
        private readonly IThirdPartyEventService _eventService;

        /// <summary>
        /// Inizialize controller.
        /// </summary>
        public ExportController(IThirdPartyEventService eventService)
        {
            _eventService = eventService;
        }

        /// <summary>
        /// Start action, load all events.
        /// </summary>
        /// <returns>View with all events.</returns>
        public async Task<ActionResult> Index()
        {
            var events = await _eventService.GetAllAsync();
            return View(events);
        }

        /// <summary>
        /// Details for selected event.
        /// </summary>
        /// <param name="id">Id selected event.</param>
        /// <returns>View with event.</returns>
        [HttpGet]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var item = await _eventService.GetAsync(id.Value);
            return View(item);
        }

        /// <summary>
        /// Build .json-file and export his in specified (Web.config) derictory.
        /// </summary>
        /// <param name="parameters">Flags events, which need to export.</param>
        /// <param name="fileName">New file with export.</param>
        /// <returns>View.</returns>
        [HttpPost]
        public async Task<ActionResult> ExportFile(List<int> parameters, string fileName)
        {
            if (parameters == null || !parameters.Any() || fileName == null || fileName.Trim() == string.Empty)
            {                
                return RedirectToAction("Index");
            }

            var events = await _eventService.GetAllAsync();
            var selectedEvents = events.Where(x => parameters.Contains(x.Id)).ToList();

            var exportEvents = selectedEvents.Select(x => new ExportThirdPartyEvent
            {
                Name = x.Name,
                Description = x.Description,
                LayoutName = x.LayoutName,
                VenueName = x.VenueName,
                StartDate = x.StartDate,
                EndDate = x.EndDate,
                PosterImage = x.PosterImage,
                NameImage = x.NameImage,
                Price = x.Price,
            });

            await WriteFileAsync(fileName, exportEvents);
            await _eventService.UpdateExportedAsync(selectedEvents);

            return RedirectToAction("Index");
        }

        private async Task WriteFileAsync(string fileName, IEnumerable<ExportThirdPartyEvent> collections)
        {
            string allowedFileType = WebConfigurationManager.AppSettings["AllowedFileTypes"];
            fileName = fileName.Contains(allowedFileType) ? fileName : fileName + allowedFileType;
            string path = WebConfigurationManager.AppSettings["ExportSourcePath"] + fileName;

            var options = new JsonSerializerOptions
            {
                Encoder = JavaScriptEncoder.Create(UnicodeRanges.All),
                WriteIndented = true,
            };

            FileStream stream = null;
            lock (new object())
            {
                stream = new FileStream(path, FileMode.Create, FileAccess.Write);
            }
            await JsonSerializer.SerializeAsync(stream, collections, options);
            stream.Close();
        }
    }
}

src/ThirdPartyEventEditor/ThirdPartyEventEditor/Views/Export/Details.cshtml
@model ThirdPartyEventEditor.Models.ThirdPartyEvent

@{
	ViewBag.Title = "Details";
}

<h2>@Model.Name</h2>
<br />
<img width="400" height="540" src="@Model.PosterImage" alt="" />
<br />
<br />
<p>Venue: @Model.VenueName</p>
<br />
<p>Layout: @Model.LayoutName</p>
<br />
<p>@Model.Description</p>
<br />
<br />
<p>Price: @Model.Price</p>
<br />
<p>Start: @Model.StartDate</p>
<br />
<p>End: @Model.EndDate</p>
<br />

src/ThirdPartyEventEditor/ThirdPartyEventEditor/Views/Export/Index.cshtml
@model System.Collections.Generic.IEnumerable<ThirdPartyEventEditor.Models.ThirdPartyEvent>

@{ ViewBag.Title = "View"; }

<style>
	.ch-select {
		width: 20px;
		height: 20px;
	}
	li {
		color: red;
		font-size: 18px;
	}
</style>

<h2>Events</h2>
@using (Html.BeginForm("ExportFile", "Export", FormMethod.Post))
{
<table class="table table-striped">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.Name)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.StartDate)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.EndDate)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Description)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.PosterImage)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Exported)
		</th>
		<th>Details</th>
		<th>Add to file</th>
	</tr>

	@foreach (var item in Model)
	{
<tr>
	<td>
		@Html.DisplayFor(modelItem => item.Name)
	</td>
	<td>
		@Html.DisplayFor(modelItem => item.StartDate)
	</td>
	<td>
		@Html.DisplayFor(modelItem => item.EndDate)
	</td>
	<td>
		@Html.DisplayFor(modelItem => item.Description)
	</td>
	<td>
		<img width="120" height="160" src="@item.PosterImage" alt="" />
	</td>
	<td>
		@if (item.Exported)
		{
<p style="color:red">Exported!</p> }
					else
					{
<p style="color:green">While not exported</p>}
	</td>
	<td>
		@Html.ActionLink("Details", "Details", new { id = item.Id })
	</td>
	<td>
		<input class="ch-select" type="checkbox" name="parameters" value="@item.Id">
	</td>

</tr>}

</table>

<label>Write name for new file: (new file will be located, indicated in configuration)</label>
<br />
<input type="text" name="fileName" value="" />
<br />
<br />
<input type="submit" value="Export" />
}