src/TicketManagement.WebApplication/Controllers/ThirdPartyEventController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using TicketManagement.WebApplication.Clients;

namespace TicketManagement.WebApplication.Controllers
{
    /// <summary>
    /// Provides operation for fetching the import file, adding and displaying third-party events.
    /// </summary>
    [Authorize(Roles = "ModeratorEvent")]
    public class ThirdPartyEventController : Controller
    {
        private readonly IEventRestClient _eventClient;

		/// <summary>
		/// Initializes a new instance of the <see cref="ThirdPartyEventController"/> class.
        /// Initializes services.
		/// </summary>
		/// <param name="eventClient">Client for eventAPI.</param>
        public ThirdPartyEventController(IEventRestClient eventClient)
        {
            _eventClient = eventClient;
        }

        /// <summary>
        /// Start page.
        /// </summary>
        /// <returns>Start view.</returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Load selected import file in system.
        /// Saving file and processing.
        /// </summary>
        /// <param name="uploadedFile">Selected file.</param>
        /// <returns>View with third-party events.</returns>
        [HttpPost]
        public async Task<IActionResult> AddFile(IFormFile uploadedFile)
        {
            if (uploadedFile != null)
            {
                var proccessEvents = await _eventClient.AddFile(uploadedFile, HttpContext.Request.Cookies["Token"]);
                ViewData["Message"] = proccessEvents.FirstOrDefault().Key;
                return View(proccessEvents.FirstOrDefault().Value);
            }

            return RedirectToAction("Index");
        }
    }
}

src/TicketManagement.WebApplication/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.FeatureManagement.Mvc;
using System.Threading.Tasks;
using TicketManagement.ClientModels.Users;
using TicketManagement.WebApplication.Clients;
using TicketManagement.WebApplication.Settings;

namespace TicketManagement.WebApplication.Controllers
{
	/// <summary>
	/// Provides operations for managing a user account.
	/// Not available for Admin role.
	/// </summary>
	[FeatureGate(FeatureFlags.UseOnlyMvc)]
	[Authorize(Roles = "User, ModeratorEvent, ModeratorVenue")]
	public class UserController : Controller
	{
		private readonly IUserRestClient _userClient;

		public UserController(IUserRestClient userClient)
		{
			_userClient = userClient;
		}

		public async Task<IActionResult> Index()
		{
			var model = await _userClient.GetUser(HttpContext.Request.Cookies["Token"]);
			return View(model);
		}

		[HttpGet]
		public async Task<IActionResult> UpdateSettings()
		{
			var model = await _userClient.GetUserSettings(HttpContext.Request.Cookies["Token"]);
			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> UpdateSettings(UserModel model)
		{
			await _userClient.UpdateUserSettings(model, HttpContext.Request.Cookies["Token"]);
			return RedirectToAction("Exit", "Account");
		}

		[HttpGet]
		public async Task<IActionResult> UpBalance()
		{
			var viewModel = await _userClient.GetUserBalance(HttpContext.Request.Cookies["Token"]);
			return View(viewModel);
		}

		[HttpPost]
		public async Task<IActionResult> UpBalance(UserModel model)
		{
			await _userClient.TopUpUserBalance(model, HttpContext.Request.Cookies["Token"]);
			return RedirectToAction("Index", "Home");
		}
	}
}

src/TicketManagement.WebApplication/Views/User/Index.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@using TicketManagement.ClientModels.Accounts; 

@model TicketManagement.ClientModels.Users.UserTicketsModel
@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{ var requestCulture = Context.Features.Get<IRequestCultureFeature>();
	var cultureItems = LocOptions.Value.SupportedUICultures
		.Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
		.ToList();
	var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}"; }

@{ ViewData["Title"] = Localizer["TitleName"]; }

<link rel="stylesheet" href="~/css/users/user.css" />

<div class="wrapper">

	<div class="user-info">
		<h2>@Localizer["InfoAboutUser"]</h2>

		<div class="action-block">
			<a class="ref-action up-score-action" asp-action="UpBalance">@Localizer["TopUpBalance"]</a>
			<a class="ref-action up-user-action" asp-action="UpdateSettings">@Localizer["Update"]</a>
			@if (Model.User.State == RoleState.ModeratorEvent)
			{
				<a class="ref-action management-action" asp-controller="ModeratorEvent" asp-action="Index" >@Localizer["EventManagement"]</a>
				<a class="ref-action management-action" asp-controller="ThirdPartyEvent" asp-action="Index" >@Localizer["ThirdPartyEventManagement"]</a>
			}
			else if (Model.User.State == RoleState.ModeratorVenue)
			{
				<a class="ref-action management-action" asp-controller="ModeratorVenue" asp-action="Index" >@Localizer["VenueManagement"]</a>
			}
			<a class="ref-action exit-action" asp-controller="Account" asp-action="Exit">@Localizer["Exit"]</a>
		</div>

		<div id="user-hover-none" class="user-info-block" title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
			<form id="formLanguage" asp-controller="Home"
				  asp-action="SetLanguage" asp-route-returnUrl="@returnUrl"
				  method="post" role="form">
				<label class="label-language" asp-for="@requestCulture.RequestCulture.UICulture.Name">@Localizer["Language:"]</label>
				<select class="select-language" name="culture"
						onchange="this.form.submit();"
						asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
				</select>
			</form>
		</div>

		<div class="user-info-block">
			<div class="permanent-user-block">@Localizer["Name"]:</div>
			<div class="user-value-block">@Model.User.Name</div>
		</div>
		<div class="user-info-block">
			<div class="permanent-user-block">@Localizer["Surname"]:</div>
			<div class="user-value-block">@Model.User.Surname</div>
		</div>
		<div class="user-info-block">
			<div class="permanent-user-block">@Localizer["Email"]:</div>
			<div class="user-value-block">@Model.User.Email</div>
		</div>
		<div class="user-info-block">
			<div class="permanent-user-block">@Localizer["Age"]:</div>
			<div class="user-value-block">@Model.User.Age</div>
		</div>
		<div class="user-info-block">
			<div class="permanent-user-block">@Localizer["Login"]:</div>
			<div class="user-value-block">@Model.User.Login</div>
		</div>
		<div class="user-info-block">
			<div class="permanent-user-block">@Localizer["Score"], $:</div>
			<div class="user-value-block">@Model.User.Score</div>
		</div>

	</div>

	<h2 class="h2-ticket">@Localizer["BoughtTickets"]</h2>
	<table style="margin-bottom: 10%;" class="table table-striped">
		<thead>
			<tr>
				<td>@Localizer["TicketDate"]</td>
				<td>@Localizer["TicketEventName"]</td>
				<td>@Localizer["TicketPrice"], $</td>
			</tr>
		</thead>

		@foreach (var item in Model.Tickets)
		{
<tr>
	<td>@item.DateTimePurchase.ToShortDateString()</td>
	<td>@item.EventName</td>
	<td>@item.Price</td>
</tr>
}
	</table>


</div>

src/TicketManagement.WebApplication/Views/User/UpBalance.cshtml
@using Microsoft.AspNetCore.Mvc.Localization; 

@model TicketManagement.ClientModels.Users.UserModel;
@inject IViewLocalizer Localizer;

@{
	ViewData["Title"] = Localizer["TitleName"];
}

<link rel="stylesheet" href="~/css/users/user-score.css" />

<div class="wrapper">

	<h2>@Localizer["UpBalance"]</h2>
	<div class="user-score">@Localizer["YourBalance"]: @Model.Score</div>

	<form method="post">
		<input style="display: none" name="id" value="@Model.Id">

		<label>@Localizer["EnterScore"]:</label><br />
		<input type="number" required min="1" max="1000000" name="score" value="" />

		<input class="btn-add" type="submit" value="@Localizer["Accept"]" />
	</form>

</div>

src/TicketManagement.WebApplication/Views/User/UpdateSettings.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;

@model TicketManagement.ClientModels.Users.UserModel;
@inject IViewLocalizer Localizer;

@{
	ViewData["Title"] = Localizer["TitleName"];
}

<link rel="stylesheet" href="~/css/login.css" />

<form class="form-register" method="post" asp-anti-forgery="true">
	<h3>@Localizer["UpdateSettings"]</h3>
	<div class="form-left">
		<div>
			<label asp-for="Name">@Localizer["EnterName"]</label>
			<input asp-for="Name" required maxlength="30" value="@Model.Name" />
			<span asp-validation-for="Name" />
		</div>
		<div>
			<label asp-for="Surname">@Localizer["EnterSurname"]</label>
			<input asp-for="Surname" required maxlength="40" value="@Model.Surname" />
			<span asp-validation-for="Surname" />
		</div>
		<div>
			<label asp-for="Age">@Localizer["EnterAge"]</label>
			<input type="number" required max="120" min="3" asp-for="Age" value="@Model.Age" />
			<span asp-validation-for="Age" />
		</div>
		<div>
			<label asp-for="Email">@Localizer["EnterEmail"]</label>
			<input type="email" required maxlength="40" asp-for="Email" value="@Model.Email" />
			<span asp-validation-for="Email" />
		</div>
	</div>

	<div class="form-right">
		<div>
			<label asp-for="Login">@Localizer["EnterLogin"]</label>
			<input type="text" required maxlength="60" asp-for="Login" value="@Model.Login" />
			<span asp-validation-for="Login" />
		</div>
		<div>
			<label asp-for="Password">@Localizer["EnterPassword"]</label>
			<input asp-for="Password"required maxlength="60" value="@Model.Password" />
			<span asp-validation-for="Password" />
		</div>
		<div>
			<input class="input-sign-in" type="submit" value="@Localizer["Save"]" />
		</div>
	</div>
</form>